---
deployment:
    tasks:
        - export DEPLOYPATH=/home/diarsqts/public_html/
        - /bin/cp -R client $DEPLOYPATH
        - /bin/cp -R server $DEPLOYPATH
        - /bin/cp app.js $DEPLOYPATH
        - /bin/cp package.json $DEPLOYPATH
        - /bin/cp yarn.lock $DEPLOYPATH
        - /bin/cp LICENSE $DEPLOYPATH
        - /bin/cp .env.example $DEPLOYPATH/.env
        - cd $DEPLOYPATH && npm install
