export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const RENDER_SIGNIN_COMPONENT = 'RENDER_SIGNIN_COMPONENT';
export const REQUEST_SIGNIN_STARTED = 'REQUEST_SIGNIN_STARTED';
export const REQUEST_SIGNIN_SUCCESS = 'REQUEST_SIGNIN_SUCCESS';
export const REQUEST_SIGNIN_FAILED = 'REQUEST_SIGNIN_FAILED';

export const REQUEST_SIGNOUT_SUCCESS = 'REQUEST_SIGNOUT_SUCCESS';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SHOW = 'SIGNUP_SHOW';
export const RENDER_SIGNUP_COMPONENT = 'RENDER_SIGNUP_COMPONENT';
export const REQUEST_SIGNUP_CANCEL = 'REQUEST_SIGNUP_CANCEL';
export const REQUEST_SIGNUP_SUCCESS = 'REQUEST_SIGNUP_SUCCESS';
export const REQUEST_SIGNUP_STARTED = 'REQUEST_SIGNUP_STARTED';

export const WORKOUT_FETCH_SUCCESS = 'WORKOUT_FETCH_SUCCESS';
export const WORKOUT_VIEWED_SET = 'WORKOUT_VIEWED_SET';
export const WORKOUT_SESSION_CREATE_SUCCESSFUL = 'WORKOUT_SESSION_CREATE_SUCCESSFUL';
export const WORKOUT_SESSION_DELETE_SUCCESSFUL = 'WORKOUT_SESSION_DELETE_SUCCESSFUL';
export const WORKOUT_SESSION_UPDATE_SUCCESSFUL = 'WORKOUT_SESSION_UPDATE_SUCCESSFUL';
export const WORKOUT_CREATE_SUCCESSFUL = 'WORKOUT_CREATE_SUCCESSFUL';
export const WORKOUT_DELETE_SUCCESSFUL = 'WORKOUT_DELETE_SUCCESSFUL';
export const RENDER_WORKOUT_COMPONENT = 'RENDER_WORKOUT_COMPONENT';