export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SHOW = 'SIGNUP_SHOW';

export const WORKOUT_FETCH_SUCCESS = 'WORKOUT_FETCH_SUCCESS';
export const WORKOUT_VIEWED_SET = 'WORKOUT_VIEWED_SET';
export const WORKOUT_SESSION_CREATE_SUCCESSFUL = 'WORKOUT_SESSION_CREATE_SUCCESSFUL';
export const WORKOUT_SESSION_DELETE_SUCCESSFUL = 'WORKOUT_SESSION_DELETE_SUCCESSFUL';
export const WORKOUT_SESSION_UPDATE_SUCCESSFUL = 'WORKOUT_SESSION_UPDATE_SUCCESSFUL';
export const WORKOUT_CREATE_SUCCESSFUL = 'WORKOUT_CREATE_SUCCESSFUL';
export const WORKOUT_DELETE_SUCCESSFUL = 'WORKOUT_DELETE_SUCCESSFUL';
